// <auto-generated />
using System;
using BudgetTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetTracker.Api.Data.Migrations
{
    [DbContext(typeof(BudgetTrackerDbContext))]
    [Migration("20260313044828_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BudgetTracker.Api.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDefault = true,
                            Name = "식비",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 2,
                            IsDefault = true,
                            Name = "교통",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 3,
                            IsDefault = true,
                            Name = "주거",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 4,
                            IsDefault = true,
                            Name = "통신",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 5,
                            IsDefault = true,
                            Name = "의료",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 6,
                            IsDefault = true,
                            Name = "문화/여가",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 7,
                            IsDefault = true,
                            Name = "교육",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 8,
                            IsDefault = true,
                            Name = "쇼핑",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 9,
                            IsDefault = true,
                            Name = "기타지출",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 10,
                            IsDefault = true,
                            Name = "급여",
                            Type = "Income"
                        },
                        new
                        {
                            Id = 11,
                            IsDefault = true,
                            Name = "부수입",
                            Type = "Income"
                        },
                        new
                        {
                            Id = 12,
                            IsDefault = true,
                            Name = "기타수입",
                            Type = "Income"
                        });
                });

            modelBuilder.Entity("BudgetTracker.Api.Models.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PointBudgetId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PointBudgetId")
                        .IsUnique();

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDefault = true,
                            Name = "현금",
                            Type = "Cash"
                        },
                        new
                        {
                            Id = 2,
                            IsDefault = true,
                            Name = "카드",
                            Type = "Card"
                        });
                });

            modelBuilder.Entity("BudgetTracker.Api.Models.Entities.PointBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RemainingAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PointBudgets");
                });

            modelBuilder.Entity("BudgetTracker.Api.Models.Entities.RecurringTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Memo")
                        .HasColumnType("text");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer");

                    b.Property<int?>("RemainingInstallments")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalInstallments")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("RecurringTransactions");
                });

            modelBuilder.Entity("BudgetTracker.Api.Models.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsIncludedInTotal")
                        .HasColumnType("boolean");

                    b.Property<string>("Memo")
                        .HasColumnType("text");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer");

                    b.Property<int?>("RecurringTransactionId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("RecurringTransactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BudgetTracker.Api.Models.Entities.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MonthStartDay")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MonthStartDay = 1
                        });
                });

            modelBuilder.Entity("BudgetTracker.Api.Models.Entities.PaymentMethod", b =>
                {
                    b.HasOne("BudgetTracker.Api.Models.Entities.PointBudget", "PointBudget")
                        .WithOne("PaymentMethod")
                        .HasForeignKey("BudgetTracker.Api.Models.Entities.PaymentMethod", "PointBudgetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PointBudget");
                });

            modelBuilder.Entity("BudgetTracker.Api.Models.Entities.RecurringTransaction", b =>
                {
                    b.HasOne("BudgetTracker.Api.Models.Entities.Category", "Category")
                        .WithMany("RecurringTransactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetTracker.Api.Models.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("RecurringTransactions")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("BudgetTracker.Api.Models.Entities.Transaction", b =>
                {
                    b.HasOne("BudgetTracker.Api.Models.Entities.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetTracker.Api.Models.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetTracker.Api.Models.Entities.RecurringTransaction", "RecurringTransaction")
                        .WithMany("Transactions")
                        .HasForeignKey("RecurringTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("PaymentMethod");

                    b.Navigation("RecurringTransaction");
                });

            modelBuilder.Entity("BudgetTracker.Api.Models.Entities.Category", b =>
                {
                    b.Navigation("RecurringTransactions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BudgetTracker.Api.Models.Entities.PaymentMethod", b =>
                {
                    b.Navigation("RecurringTransactions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BudgetTracker.Api.Models.Entities.PointBudget", b =>
                {
                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("BudgetTracker.Api.Models.Entities.RecurringTransaction", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
